trigger:
  - master
  - '*.x'

variables:
  vmImage: ubuntu-latest
  python.version: '3.8'
  TOXENV: py

strategy:
  matrix:
    Linux:
      vmImage: ubuntu-latest
    Windows:
      vmImage: windows-latest
    Mac:
      vmImage: macos-latest
    Python 3.7:
      python.version: '3.7'
    Python 3.6:
      python.version: '3.6'
    PyPy:
      python.version: pypy3
    Docs:
      TOXENV: docs
    Style:
      TOXENV: style

pool:
  vmImage: $(vmImage)

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(python.version)
    displayName: Use Python $(python.version)

  - script: pip --disable-pip-version-check install -U tox
    displayName: Install tox

  - script: tox
    displayName: Run tox
